In [1]:
import numpy as np

In [3]:
a = [1,2,3]
b = [4,5,6]
c = np.array([1,2,3])
d = np.array([4,5,6])

In [4]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
c*d

array([ 4, 10, 18])

In [6]:
# One dimensional Array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
# 2D Array
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
# 3D Array
c = np.array([[[1,2,3],[1,2,5]]])
c

array([[[1, 2, 3],
        [1, 2, 5]]])

In [9]:
# Dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [10]:
# Shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(1, 2, 3)


In [11]:
# Type 
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int32


In [12]:
a = np.array([1,2,3],dtype='int16')
print(a.dtype)

int16


In [13]:
# Size
print(a.itemsize)
print(b.itemsize)
print(a.size)
print(b.size)

2
8
3
6


In [14]:
print(b.itemsize, "bytes")
print(b.dtype)

8 bytes
float64


In [15]:
#total size
print(a.size*a.itemsize)
print(a.nbytes)

6
6


### Accessing/Changing specific elements, rows, columns

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [17]:
# specific row/column
print(a[0, :], "1st row")
print(a[1, :], "2nd row")
print(a[: ,2], "2nd column")

[1 2 3 4 5 6 7] 1st row
[ 8  9 10 11 12 13 14] 2nd row
[ 3 10] 2nd column


In [18]:
# specific element
print(a[1,5])
print(a[1,-2])

13
13


In [19]:
# fancy [startindex,endindex,stepsize]
print(a[0, 1:6:2])   # 6 is exclusive
print(a[0, 1:-1:2])

[2 4 6]
[2 4 6]


In [20]:
# Changing an element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [21]:
# Changing a column
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [22]:
# Changing a column
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


<i><b> 3D Example

In [23]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a[0,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


In [24]:
print(a[:,1,:],"\n\n")
print(a[:,0,:],"\n\n")
print(a[:,1,1],"\n\n")

[[3 4]
 [7 8]] 


[[1 2]
 [5 6]] 


[4 8] 




In [25]:
print(a)
print(a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [26]:
# replacing in 3D

a[:,1,:] = [[9,9],[8,8]]
a

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing different types of Arrays

In [27]:
np.zeros(5)   # 1D

array([0., 0., 0., 0., 0.])

In [28]:
# All zeros matrix
np.zeros((2,3,3,2))  #4D

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [29]:
# All ones matrix
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [30]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [31]:
np.full((2,2),"a")

array([['a', 'a'],
       ['a', 'a']], dtype='<U1')

In [32]:
np.full_like(a,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [33]:
np.full(a.shape,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [34]:
#Random Decimal Numbers Array
np.random.rand(5)

array([0.88136439, 0.4507311 , 0.60594818, 0.98992054, 0.48865825])

In [35]:
np.random.rand(4,2,3)

array([[[0.77657837, 0.22678062, 0.29125066],
        [0.59147317, 0.58055497, 0.8522246 ]],

       [[0.69240333, 0.48605359, 0.48180638],
        [0.72942776, 0.02457528, 0.41994781]],

       [[0.00452694, 0.14974687, 0.8853222 ],
        [0.82715547, 0.73931623, 0.83410429]],

       [[0.34296313, 0.75145135, 0.58278659],
        [0.03111901, 0.42408009, 0.4280408 ]]])

In [36]:
np.random.random_sample(a.shape)

array([[[0.15503957, 0.3257593 ],
        [0.98255857, 0.16142891]],

       [[0.59291365, 0.07724088],
        [0.53783846, 0.49800919]]])

In [37]:
# Random Integer Numbers Array
np.random.randint(7)

4

In [38]:
np.random.randint(7,size=(3,3))

array([[5, 2, 3],
       [5, 6, 2],
       [2, 4, 0]])

In [39]:
np.random.randint(-4,7,size=(3,3))

array([[-4,  6, -1],
       [ 0,  1, -3],
       [-4,  5,  5]])

In [40]:
# Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# Repeating an Array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [42]:
arr = np.array([[1,2,3]])
r2 = np.repeat(arr,3,axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [43]:
r2 = np.repeat(arr,3,axis=1)
print(r2)

[[1 1 1 2 2 2 3 3 3]]


### Problem # 1

<i><b> Method # 1

In [65]:
a = np.array(np.ones((5,5),dtype='int16'))
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [67]:
a[1:-1,1:-1] = 0    # a[rows,coulums] = a[row2:row2ndlast,col2:col2ndlast]
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [84]:
a[2,2] = 9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


<i><b> Method # 2 <b><i>

In [90]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [91]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathematics

In [3]:
a = np.array([1,2,3,4])

In [4]:
a+2

array([3, 4, 5, 6])

In [5]:
a-2

array([-1,  0,  1,  2])

In [6]:
a*2

array([2, 4, 6, 8])

In [7]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [10]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [9]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [11]:
b = np.array([5,6,7,8])
b+a

array([ 6,  8, 10, 12])

In [13]:
a+=2
a

array([5, 6, 7, 8])

### Linear Algebra

In [21]:
# Multiplying matrices
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [23]:
# Determinant of a Matrix
c = np.identity(3)
print(c)

np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

### Statistics

In [2]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print(np.min(stats))
print(np.min(stats, axis=0))
print(np.min(stats, axis=1))

1
[1 2 3]
[1 4]


In [10]:
print(np.max(stats))
print(np.max(stats, axis=0))
print(np.max(stats, axis=1))

6
[4 5 6]
[3 6]


In [12]:
np.sum(stats)

21

In [15]:
print(np.sum(stats, axis=1))
print(np.sum(stats, axis=0))

[ 6 15]
[5 7 9]


### Reorganizing Arrays

In [24]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape, "Shape")
print(before)

after = before.reshape((8,1))
print(after)

(2, 4) Shape
[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [25]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [34]:
# Horizontal Stacking Vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Loading Data from File

In [10]:
filedata = np.genfromtxt("data.txt",delimiter=",")
filedata.astype("int32")
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.]])

In [11]:
filedata = np.genfromtxt("data.txt",delimiter=",")
filedata = filename.astype("int32")
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78]])

### Boolean Masking and Advanced Indexing

In [12]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False],
       [False, False, False, False,  True, False, False, False,  True]])

In [13]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78])

In [15]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [16]:
# Checks if any value in a column is greater than 50
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True])

In [17]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False])

In [18]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [26]:
((filedata) > 50 & (filedata < 100))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [27]:
~((filedata) > 50 & (filedata < 100))

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

### Problem # 2

In [58]:
a = np.array([i for i in range(1,31)]).reshape(6,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [62]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [63]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [65]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [60]:
a = np.arange(1,31).reshape(6,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
